name: Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  appsec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install security tools
      run: |
        pip install bandit safety semgrep
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64 -o gitleaks
        chmod +x gitleaks && sudo mv gitleaks /usr/local/bin/

    - name: Run Bandit
      run: bandit -r vulnerable_code || true

    - name: Run Semgrep
      run: semgrep --config=auto vulnerable_code || true

    - name: Run Safety
      run: safety check -r vulnerable_code/requirements.txt || true

    - name: Run Gitleaks
      run: gitleaks detect --source=. --no-git || true

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Install Maven
      uses: s4u/setup-maven-action@v1

    - name: Build and Run App
      run: |
        mvn clean package -DskipTests
        java -jar target/*.jar &
        sleep 15

    - name: Semgrep (SAST)
      uses: returntocorp/semgrep-action@v1
      with:
        config: auto

    - name: OWASP Dependency Check (SCA)
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "dv-spring-app"
        path: "."
        format: "HTML"

    - name: Gitleaks (секрет-сканер)
      uses: gitleaks/gitleaks-action@v2
      env:
        GITLEAKS_LICENSE: accept

    - name: OWASP ZAP Baseline Scan (DAST)
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:8080'
      continue-on-error: true
