name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  appsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Start app in background
        run: |
          java -jar build/libs/*.jar &
          sleep 20

      - name: Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

      - name: OWASP Dependency-Check (SCA)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "dvsb-app"
          path: "."
          format: "HTML"

      - name: Gitleaks (Secrets Scan)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: accept

      - name: OWASP ZAP Baseline Scan (DAST)
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8080'
        continue-on-error: true
