name: AppSec CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  appsec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python deps and security tools
      run: |
        pip install -r requirements.txt || true
        pip install safety semgrep

    - name: Install Gitleaks
      run: |
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64 -o gitleaks
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/gitleaks

    - name: Install OSV-Scanner binary
      run: |
        curl -sLO https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64
        chmod +x osv-scanner-linux-amd64
        sudo mv osv-scanner-linux-amd64 /usr/local/bin/osv-scanner

    - name: Run Safety (Python vuln DB)
      run: |
        safety check -r requirements.txt --full-report > safety-report.txt || true

    - name: Run OSV-Scanner
      run: |
        osv-scanner --lockfile=requirements.txt --format json > osv-report.json || true

    - name: Run Gitleaks (secret scan)
      run: |
        gitleaks detect --source=. --report-format=json --report-path=gitleaks-report.json || true

    - name: Run Semgrep (SAST)
      run: |
        semgrep --config=auto --json > semgrep-report.json || true

    - name: Upload scan reports
      uses: actions/upload-artifact@v4
      with:
        name: appsec-reports
        path: |
          safety-report.txt
          osv-report.json
          gitleaks-report.json
          semgrep-report.json
