name: AppSec CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  appsec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        pip install semgrep
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
        chmod +x gitleaks && sudo mv gitleaks /usr/local/bin/

    - name: Build Spring Boot app
      working-directory: app
      run: |
        ./mvnw clean package -DskipTests
        java -jar target/*.jar &
        sleep 20

    - name: Semgrep (SAST)
      run: semgrep --config=auto .

    - name: Gitleaks (секрет-сканер)
      run: gitleaks detect --source=. --no-git || true

    - name: OWASP Dependency-Check (SCA)
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "dvsb-app"
        path: "./app"
        format: "HTML"

    - name: OWASP ZAP (DAST)
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:8080'
      continue-on-error: true
