name: AppSec CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  appsec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install security tools
      run: |
        pip install -r requirements.txt || true
        pip install safety semgrep

        # Install osv-scanner safely via tar.gz
        curl -sLO https://github.com/google/osv-scanner/releases/latest/download/osv-scanner_1.6.2_linux_amd64.tar.gz
        tar -xzf osv-scanner_1.6.2_linux_amd64.tar.gz
        sudo mv osv-scanner /usr/local/bin/
        rm osv-scanner_1.6.2_linux_amd64.tar.gz

        # Install Gitleaks
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64 -o gitleaks
        chmod +x gitleaks && sudo mv gitleaks /usr/local/bin/

    - name: Run Safety (Python vuln DB)
      run: |
        safety check -r requirements.txt --full-report > safety-report.txt || true

    - name: Run OSV-Scanner
      run: |
        osv-scanner --lockfile=requirements.txt --format json > osv-report.json || true

    - name: Run Gitleaks
      run: |
        gitleaks detect --source=. --report-format=json --report-path=gitleaks-report.json || true

    - name: Run Semgrep
      run: |
        semgrep --config=auto --json > semgrep-report.json || true

    - name: Upload AppSec Reports
      uses: actions/upload-artifact@v4
      with:
        name: appsec-reports
        path: |
          safety-report.txt
          osv-report.json
          gitleaks-report.json
          semgrep-report.json
