name: Security Checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  appsec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install security tools
      run: |
        pip install bandit safety semgrep
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64 -o gitleaks
        chmod +x gitleaks && sudo mv gitleaks /usr/local/bin/

    - name: Run Bandit
      run: bandit -r vulnerable_code || true

    - name: Run Semgrep
      run: semgrep --config=auto vulnerable_code || true

    - name: Run Safety
      run: safety check -r vulnerable_code/requirements.txt || true

    - name: Run Gitleaks
      run: gitleaks detect --source=. --no-git || true
