name: AppSec Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  appsec:
    name: AppSec Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install security tools
      run: |
        pip install safety
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64 -o gitleaks
        chmod +x gitleaks && sudo mv gitleaks /usr/local/bin/
        curl -sLO https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64
        chmod +x osv-scanner-linux-amd64 && sudo mv osv-scanner-linux-amd64 /usr/local/bin/osv-scanner

    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: auto
      continue-on-error: true  # не ломает pipeline

    - name: Run Gitleaks
      run: gitleaks detect --source=. --no-git --report-format sarif --report-path gitleaks.sarif || true

    - name: Run Safety (Python SCA)
      run: |
        safety check -r requirements.txt --json > safety-report.json || true

    - name: Run OSV Scanner (Universal SCA)
      run: |
        osv-scanner --lockfile=requirements.txt --format json > osv-report.json || true

    - name: Upload Security Reports
      uses: actions/upload-artifact@v4
      with:
        name: appsec-reports
        path: |
          *.json
          *.sarif
        if-no-files-found: warn
